version: 2
updates:
- package-ecosystem: cargo
  directory: "/tutara-wasm"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/tutara-cli"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/tutara-interpreter"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
