name: cargo

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo build
        run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo test
        run: cargo test --verbose
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo clippy
        run: cargo clippy --verbose
