name: Rust - Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  tutara-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: Build using wasm-pack
        run: wasm-pack build --target web --scope tutara
        working-directory: ./tutara-wasm/
      - uses: actions/upload-artifact@v2
        with:
          name: WebAssembly package
          path: ./tutara-wasm/pkg/
